// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using LinqToRdf;
namespace RdfSerialisationTest
{
	[TestClass()]
	public class OwlInstanceSupertypeTest
	{


		private TestContext testContextInstance;

		public TestContext TestContext
		{
			get
			{
				return testContextInstance;
			}
			set
			{
				testContextInstance = value;
			}
		}
		#region Additional test attributes
		// 
		//You can use the following additional attributes as you write your tests:
		//
		//Use ClassInitialize to run code before running the first test in the class
		//
		//[ClassInitialize()]
		//public static void MyClassInitialize(TestContext testContext)
		//{
		//}
		//
		//Use ClassCleanup to run code after all tests in ontology class have run
		//
		//[ClassCleanup()]
		//public static void MyClassCleanup()
		//{
		//}
		//
		//Use TestInitialize to run code before running each test
		//
		//[TestInitialize()]
		//public void MyTestInitialize()
		//{
		//}
		//
		//Use TestCleanup to run code after each test has run
		//
		//[TestCleanup()]
		//public void MyTestCleanup()
		//{
		//}
		//
		#endregion


		internal class MyTestClass
		{
			private int myTestField;

			public int MyTestField
			{
				get { return myTestField; }
				set { myTestField = value; }
			}
		}

		[TestMethod()]
		public void InstanceUriTest()
		{
			OwlInstanceSupertype target = new OwlInstanceSupertype();

			string val = "http://tempuri.net/uri"; // TODO: Assign to an appropriate value for the property

			target.InstanceUri = val;


			Assert.AreEqual(val, target.InstanceUri, "LinqToRdf.OwlInstanceSupertype.InstanceUri was not set correctly.");
		}

	}


}
