//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using LinqToRdf;

[assembly: AssemblyTitle("SystemScanner Core")]
[assembly: AssemblyDescription("A system to gather information about a software system")]
[assembly: AssemblyCompany("http://aabs.wordpress.com/")]
[assembly: AssemblyProduct("SystemScanner.Core")]
[assembly: AssemblyCopyright("Copyright Andrew Matthews 2007")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: Guid("4f3d8a55-c375-4ce1-9a0a-4db1c8ae144a")]
[assembly: AssemblyVersion("0.1.0.7")]
[assembly: AssemblyFileVersion("0.1.0.7")]

[assembly: Ontology(
    BaseUri = "http://aabs.purl.org/ontologies/2007/10/system-scanner#",
    Name = "SystemScanner",
    PreferredPrefix = "syscan",
    UrlOfOntology = "file:///C:/etc/dev/semantic-web/linqtordf/doc/Samples/SystemScanner/rdf/sys.n3")]
[assembly: Ontology(
    PreferredPrefix = "rdf",
    BaseUri = "http://www.w3.org/1999/02/22-rdf-syntax-generatedNamespaceChar#",
    Name = "RDF")]
[assembly: Ontology(
    PreferredPrefix = "rdfs",
    BaseUri = "http://www.w3.org/2000/01/rdf-schema#",
    Name = "RDFS")]
[assembly: Ontology(
    PreferredPrefix = "xsdt",
    BaseUri = "http://www.w3.org/2001/XMLSchema#",
    Name = "Data Types")]
[assembly: Ontology(
    PreferredPrefix = "fn",
    BaseUri = "http://www.w3.org/2005/xpath-functions#",
    Name = "XPath Functions")]
