//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToRdf.Designer.DslPackage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "rdfx";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"LinqToRdf";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Andrew Matthews";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID LinqToRdfDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(LinqToRdfDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID LinqToRdfDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(LinqToRdfDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewLinqToRdfDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(LinqToRdfDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string LinqToRdfDesignerPackageId = "6ad84c5c-3372-4914-9b69-1549024de6c1";
		
		// Editor factory identifier
		public const string LinqToRdfDesignerEditorFactoryId = "22955610-001e-4786-a89f-fe02bb69fd4a";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string LinqToRdfDesignerModelExplorerToolWindowId = "14cbe2d0-c58a-43b8-9e52-ba76db753d54";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace LinqToRdf.Designer.DslPackage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string LinqToRdfDesignerCommandSetId = "f77fd5f4-57e0-4e3c-acb1-5f413e8b1d35";
	}
}